# Generated by Django 5.0.1 on 2024-01-10 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionario', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('idModelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modelo', models.CharField(max_length=255)),
                ('numero_puertas', models.IntegerField()),
                ('tipo_motor', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='coche',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='coche',
            name='tipo_coche',
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('idVehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idmarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionario.marca')),
                ('idmodelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionario.modelo')),
            ],
        ),
        migrations.DeleteModel(
            name='MarcaCoche',
        ),
        migrations.DeleteModel(
            name='Coche',
        ),
        migrations.DeleteModel(
            name='TipoCoche',
        ),
    ]
